## Methods

Two sample size calculations are required...

* Test of proportions.
* Ordinal regression based on three levels of pre-categorised risk.


Full details of the original sample size calculation performed by [Mike Bradburn](mailto:m.bradburn@sheffield.ac.uk) can be found in the file...

> `../projects/CTRU/CTRU jobs/2017/J17-07 Griffiths High risk pregnancy/Stats/Sample size/Original/Meridian high risk sample size.do`

A copy is included in the Appendix for reference.

### Test of Proportions

This is straight-forward and can be derived empirically from a sample size calculation for a test of two propotions.  In R this is available in the [`pwr`](https://cran.r-project.org/web/packages/pwr/index.html) package which provides the function `pwr.2p.test()` which takes the effect size in terms of [Cohens d](https://en.wikipedia.org/wiki/Effect_size#Cohen.27s_d).  It provides the helper function `ES.h()` to calculate Cohens d for any pair of proportions.


### Ordinal Regression

This is much more involved and is highly dependant on the number of individuals in category.  The existing sample size calculation has used a simulation approach, defining the risk to each category (presumably in absolute terms as risks for each category are specified) and the prevalence of each (presumably in terms of the ratio of individuals within each category).  The combinations that have been tested are...

| Simulation | Risk 1 | Risk 2 | Risk 3 | Prevalance 1 | Prevalance 2 | Prevalance 3 |
|------------|--------|--------|--------|--------------|--------------|--------------|
| 1          | 0.01   | 0.05   | 0.1    | 1            | 1            | 1            |
| 2          | 0.01   | 0.05   | 0.1    | 1            | 2            | 1            |
| 3          | 0.01   | 0.05   | 0.15   | 9            | 3            | 1            |
| 4          | 0.01   | 0.2    | 0.4    | 12           | 4            | 1            |
